# Generated by Django 3.0.8 on 2021-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
