# Generated by Django 3.0.8 on 2021-03-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210326_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('like_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.Profile')),
            ],
        ),
    ]
